apiVersion: v1
data:
  mongodb-root-password: cERSbDNxMWNMWg==
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mongodb-root-password":"cERSbDNxMWNMWg=="},"kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"mongodb","app.kubernetes.io/instance":"mongodb","app.kubernetes.io/managed-by":"Helm","app.kubernetes.io/name":"mongodb","app.kubernetes.io/version":"7.0.5","helm.sh/chart":"mongodb-14.5.0"},"name":"mongodb","namespace":"anoti-mongo"},"type":"Opaque"}
  creationTimestamp: "2024-01-11T22:37:44Z"
  labels:
    app.kubernetes.io/component: mongodb
    app.kubernetes.io/instance: mongodb
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: mongodb
    app.kubernetes.io/version: 7.0.5
    helm.sh/chart: mongodb-14.5.0
  name: mongodb
  namespace: anoti-mongo
  resourceVersion: "48303"
  uid: a19a7d02-eb3a-4f52-bc9f-17d531e84f3e
type: Opaque